# Generated by Django 2.2.5 on 2019-09-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_zhoudu',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('fenlei', models.CharField(max_length=64)),
                ('score', models.CharField(max_length=64)),
                ('dwlink1', models.CharField(max_length=255)),
                ('dwlink2', models.CharField(max_length=255)),
                ('dwlink3', models.CharField(max_length=255)),
            ],
        ),
    ]
